---
title: "FeatureFilms"
author: "David Stroud"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the rvest package
library(rvest)
```

```{r}
# Specify url for desired website to be scraped
url <- 'http://www.imdb.com/search/title?count=100&release_date=2016,2016&title_type=feature'

# Read the html code from the site
webpage <- read_html(url)

```

```{r}
# Use CSS selectors to scrape the rankings section
rank_data_html <- html_nodes(webpage, '.text-primary')

# Converting the ranking data to text
rank_data <- html_text(rank_data_html)

# Look at the rankings
head(rank_data)
```

```{r}
# Data Processing: Convert rankings to numerical
rank_data <- as.numeric(rank_data)

# View the first six rankings
head(rank_data)
```

```{r}
# Use CSS selectors to scrape the title section
title_data_html <- html_nodes(webpage, '.lister-item-header a')

# Converting the title data to text
title_data <- html_text(title_data_html)

# View the first six rankings
head(title_data)
```


```{r}
# Using CSS selectors to scrape the description section
description_data_html <- html_nodes(webpage, '.ratings-bar+ .text-muted')

# Converting the title data to text
description_data <- html_text(description_data_html)

# View the first six descriptions
head(description_data)
```












