---
title: "HarryPotter"
author: "David Stroud"
date: "3/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("rvest")   # Great for grabbing and parsing HTML
library("dplyr")   # Easy transformation of data.frames for summarization
library("tidyr")   # Nice way to arrange data
library("ggplot2") # Excellent for visuals
```


### 1. Harry Potter Cast
```{r}
# a. Harry Potter Cast. Pulling data from website
url <- 'http://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1'
webpage <- read_html(url)
```

```{r}
# b. Scrape the table
webpage %>%
  html_nodes(css = "table")
```

```{r}
cast = webpage %>%
  html_nodes(".itemprop .itemprop") %>%
  html_text()
```


```{r}
# Turn actors names into a dataframe
harry_df<-data.frame(cast)

```


```{r}
# d. Split the Actor’s name into two columns:
main_actors <- extract(harry_df, cast, c("FirstName", "LastName"), "([^ ]+) (.*)")

```

```{r}
# d. Print the first ten rows of the column
head(main_actors,10)
```















