---
title: "Unit9 Homework"
author: "David Stroud"
date: "3/5/2018"
output:
  prettydoc::html_pretty:
    highlight: github
    theme: architect
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("rvest")   # Great for grabbing and parsing HTML
library("dplyr")   # Easy transformation of data.frames for summarization
library("tidyr")   # Nice way to arrange data
library("ggplot2") # Excellent for visuals
```


### 1. Harry Potter Cast
#### a. In the IMDB, there are listings of full cast members for movies. Navigate to http://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1. Feel free to View Source to get a good idea of what the page looks like in code.
```{r}
# b. Pulling data from website
url <- 'http://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1'
webpage <- read_html(url)
```

```{r}
# b. Scrape the table
webpage %>%
  html_nodes(css = "table")
```

```{r}
cast = webpage %>%
  html_nodes(".itemprop .itemprop") %>%
  html_text()
```


```{r}
# c. Clean up the table
# Turn actors names into a dataframe
harry_df<-data.frame(cast)

```


```{r}
# d. Split the Actor’s name into two columns:
main_actors <- extract(harry_df, cast, c("FirstName", "LastName"), "([^ ]+) (.*)")

```

```{r}
# e. Present the first 10 rows of the data.frame()
head(main_actors,10)
```


### 2. SportsBall  

#### a. On the ESPN website, there are statistics of each NBA player. Navigate to the San Antonio Spurs current statistics (likely http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs). You are interested in the Shooting Statistics table.

```{r}
# b.Scrape the page with any R package that makes things easy for you. There are a few tables on the page, so make sure you are targeting specifically the Shooting Statistics table.
url <- 'http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs'
site <- read_html(url)
players_table <- html_nodes(site, 'table')
players <- html_table(players_table,fill=TRUE)[[2]]
```


```{r}
players_df<-data.frame(players)
head(players)
```

```{r}
# Check the data type of all columns. Convert relevant columns to numeric
players[, c(2:15)] <- sapply(players[, c(2:15)], as.numeric, suppressWarnings(as.numeric(c("1", "2", "X"))))
```


```{r}
# Check the data type of all columns again to confirm that they have changed
sapply(players, class)
```

```{r}
View(players)
```




