---
title: "WebScraping"
author: "David Stroud"
date: "3/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 # General-purpose data wrangling
    library(tidyverse)  
    # Parsing of HTML/XML files  
    library(rvest)    
    # String manipulation
    library(stringr)   
    # Verbose regular expressions
    library(rebus)     
    # Eases DateTime manipulation
    library(lubridate)
```

```{r}
# Landing page for Amazon Review
 url <-'http://www.trustpilot.com/review/www.amazon.com'
```

```{r}
 get_last_page <- function(html){

      pages_data <- html %>% 
                      # The '.' indicates the class
                      html_nodes('.pagination-page') %>% 
                      # Extract the raw text as a list
                      html_text()                   

      # The second to last of the buttons is the one
      pages_data[(length(pages_data)-1)] %>%            
        # Take the raw string
        unname() %>%                                     
        # Convert to number
        as.numeric()                                     
    }
```

```{r}
 first_page <- read_html(url)
    (latest_page_number <- get_last_page(first_page))
```

```{r}
# Generate a list of all relevant html's
list_of_pages <- str_c(url, '?page=', 1:latest_page_number)
```

```{r}
get_reviews <- function(html) {
  html %>%
    # The relevant tag
    html_nodes('.review-body') %>%
    html_text() %>%
    # Convert the list into a vector
    unlist()
}

get_reviewers_names <- function(html) {
  html %>%
    html_nodes('.user-review-name-link') %>%
    html_text() %>%
    unlist()
}
```


```{r}
get_review_dates <- function(html){

      status <- html %>% 
                  html_nodes('time') %>% 
                  # The status information is this time a tag attribute
                  html_attrs() %>%             
                  # Extract the second element
                  map(2) %>%                    
                  unlist() 

      dates <- html %>% 
                  html_nodes('time') %>% 
                  html_attrs() %>% 
                  map(1) %>% 
                  # Parse the string into a datetime object with lubridate
                  ymd_hms() %>%                 
                  unlist()

      # Combine the status and the date information to filter one via the other
      return_dates <- tibble(status = status, dates = dates) %>%   
                        # Only these are actual reviews
                        filter(status == 'ndate') %>%              
                        # Select and convert to vector
                        pull(dates) %>%                            
                        # Convert DateTimes to POSIX objects
                        as.POSIXct(origin = '1970-01-01 00:00:00') 

      # The lengths still occasionally do not lign up. You then arbitrarily crop the dates to fit
      # This can cause data imperfections, however reviews on one page are generally close in time)

      length_reviews <- length(get_reviews(html))

      return_reviews <- if (length(return_dates)> length_reviews){
          return_dates[1:length_reviews]
        } else{
          return_dates
        }
      return_reviews
    }
```

```{r}
get_star_rating <- function(html){

      # The pattern you look for: the first digit after `count-`
      pattern = 'count-'%R% capture(DIGIT)    

      ratings <-  html %>% 
        html_nodes('.star-rating') %>% 
        html_attrs() %>% 
        # Apply the pattern match to all attributes
        map(str_match, pattern = pattern) %>%
        # str_match[1] is the fully matched string, the second entry
        # is the part you extract with the capture in your pattern  
        map(2) %>%                             

        unlist()

      # Leave out the first instance, as it is not part of a review
      ratings[2:length(ratings)]               
    }
```


```{r}
get_data_table <- function(html, company_name) {
  # Extract the basic information from the html
  reviews <- get_reviews(html)
  reviewer_names <- get_reviewers_names(html)
  dates <- get_review_dates(html)
  ratings <- get_star_rating(html)
  
  # Combine into a tibble
  combined_data <- tibble(reviewer = reviewer_names,
                          date = dates, 
                          rating = ratings,
                          review = reviews)
  
  # Tag the individual data with the company name
  combined_data %>%
    mutate(company = company_name) %>%
    select(company, reviwer, date, rating, review)
}
```














