---
title: "Unit10Homework"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# General-purpose data wrangling
    library(tidyverse)  
    # Parsing of HTML/XML files  
    library(rvest)    
    # String manipulation
    library(stringr)   
    # Verbose regular expressions
    library(rebus)     
    # Eases DateTime manipulation
    library(lubridate)
    # Easier way to use count
    library(plyr)
```

### 1. Mental Health Clinics 
```{r}
# a. Load the dataset
load("/Users/davidstroud/Dropbox/Data_Science1/DataScienceSMU/Homework/Unit10/N-MHSS-2015-DS0001-bndl-data-r/N-MHSS-2015-DS0001-data/N-MHSS-2015-DS0001-data-r.rda")
```

```{r}
# b.Create code which lists the State abbreviations without their counts
va<- (levels(mh2015_puf$LST))

```


```{r}
# c. Create a listing of the counts of all VA medical centers in the mainland US by state
va <-count(mh2015_puf$LST)
print(va)

```


```{r}
# Rename x to statename for future merging
va <- rename(va, c("x"= "StateName"))
print(va)
```


```{r}
 # c. Convert to a dataframe 
va_med_ctr <- as.data.frame(va)
print(va_med_ctr)
```

```{r}
va_med_ctr = va_med_ctr[-c(1,13,14,42,50), ]
print(va_med_ctr)
```




```{r}
# d. Create a ggplot barchart of this filtered data set.
library(ggthemes)
ggplot(data=va_med_ctr, aes(x=StateName, y=freq)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_economist() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=rel(0.8), angle=90)) +
  ggtitle("VA Centers in Mainland US") +
  theme(plot.title = element_text(hjust = 0.5))+
  labs(x="State Name",y="Number of VA Facilities")
```


### 2. Cleaning and Bringing in New Features

```{r}
# a. Read statesize.csv into your R environment
statesize <-read.csv("statesize.csv")
str(statesize)
```

```{r}
# this doesnt work
tempdata <- merge(statesize, va_med_ctr, by="StateName", all=TRUE)
```

```{r}
# c. Calculate a new variable in your combined data.frame() which indicates the VA hospitals per thousand square miles
```



















