---
title: "Unit5 Homework"
author: "David Stroud"
date: "2/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###1. Data Munging  
```{r}
# a. Import yob2016.txt and assign to df
df <- read.table('yob2016.txt',header = FALSE, sep = ';')
# Change column names
names(df)[names(df) == "V1"] <- "Names"
names(df)[names(df) == "V2"] <- "Gender"
names(df)[names(df) == "V3"] <- "Amount"

```

```{r}
# b. Display the summary and structure of df
summary(df)
str(df)
```

```{r}
# c. find three y's at the end of a name
grep("yyy", df$Names)
```

```{r}
# d. Remove misspelled name and assign data set as an object: y2016
df <- df[-212,]
y2016 <- df
```


### 2. Data Merging
```{r}
# a. Import yob2015.txt file
y2015<- read.table('yob2015.txt',header = FALSE, sep = ',')

# Change the column names
names(y2015)[names(y2015) == "V1"] <- "Names"
names(y2015)[names(y2015) == "V2"] <- "Gender"
names(y2015)[names(y2015) == "V3"] <- "Amount"
```


```{r}
# b. Display the last ten rows in the data frame
tail(y2015,10)
# It is interesting that the names are all Male and there are 5 names of each
```


```{r}
# c. Merge y2016 and y2015 by Name column and assign to final
final <- merge(y2015, y2016,by='Names',all=FALSE)
```


### 3. Data Summary
```{r}
# a. Create Column called 'Total' in final that adds the amount of children in 2015 and 2016 together. 
#     How many people were given popular names in these two years?
final$Total <- final$Amount.x + final$Amount.y
summary(final$Total)

```

### 4. Link to Unit 5 assignment on GitHub 
[Unit 5 Homework](https://github.com/davestroud/DataScience)

